### PR TITLE
Avoid comitting .env files

### PR DESCRIPTION
**Pull request by dpordomingo**
Since `.env` like files are environment dependant, should not be committed to avoiding collisions ([reasoning](https://github.com/motdotla/dotenv#should-i-commit-my-env-file))

I saw it was used to avoid relative imports in the new imports created by https://github.com/bblfsh/dashboard/pull/76 but that's not how dashboard requires its dependencies; and I find two reasons for that:
- it lets us know quickly which imports are internal, and which ones are external
- it seems to be done broadly ([react itself](https://github.com/facebook/react/blob/master/packages/react-dom/src/events/ReactDOMEventListener.js#L14), [reddit mobile](https://github.com/reddit/reddit-mobile/blob/2X/src/apiClient/apis/ActivitiesEndpoint.js#L3))

### CODE REVIEW

**Comment by smacker** [comment]
Usually I use webpack aliases for it, like this:
```
import api from '~/services/api'
```
Then you can see is it internal or external easy.

It's kind of good practice to do so for applications (not libraries as react). You can see it in many bootstrappers, few examples: [nuxtjs](https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/base.config.js#L39), [nwb](https://github.com/insin/nwb/blob/master/docs/Testing.md#importing-code-in-tests).
Others use [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver#who-is-using-babel-plugin-module-resolver-). You can see Algolia, Airbnb, Uber, Next.js there.
Even in your example of reddit mobile you can [see](https://github.com/reddit/reddit-mobile/blob/2X/src/apiClient/apis/ActivitiesEndpoint.js#L1) aliases.

Because without it refactoring is a huge pain.

Sadly react-create-app doesn't support aliases without eject. And `.env` file is recommended way to implement aliases with it: https://github.com/facebookincubator/create-react-app/issues/2188#issuecomment-302040874 (gaearon Dan Abramov is maintainer of create-react-app)

**Comment by dpordomingo** [comment]
Committing `.env` files [is not a good idea](https://github.com/motdotla/dotenv#should-i-commit-my-env-file)

Having relative imports, and "absolute" ones mixed in the project does not seems a good idea.

Having an alias for the root path, and then make all the imports relative to that one could be a good idea and will avoid `../` too, but it should be done broadly and in a separate PR.

If we want to implement an alternative to webpack aliases we should consider the alternatives in a separated issue, and face it as a separated thing

**Comment by smacker** [comment]
don't see any reasoning by link. Just recommendation without any explanation. Also it's link to a library that we don't use. Also as I noticed reading source code source-d doesn't use env variables for configuration much. Usually I see only flags for it. Please provide some arguments why we shouldn't commit or shouldn't use mixed imports.

My arguments:
- When in Rome, do as the Romans do. We use create-react-app. We should do what is recommended as long as it is possible.
- Mixed imports are common just everywhere. In almost any language and definitely in JS world. Even your example contains mixed imports! So I apply to the rule "is innocent until proven guilty"

**Comment by dpordomingo** [comment]
The link provides a strong rationale, the `.env` files _"should only include environment-specific values"_ and should be editable locally without colliding with other environmental values.

About the "recommendation of using `NODE_PATH` to workaround the lack of aliases", in that same issue it is said that this workaround does [not solve](https://github.com/facebookincubator/create-react-app/issues/2188#issuecomment-333997710) the lack of alias [nor helps](https://github.com/facebookincubator/create-react-app/issues/2188#issuecomment-331191599) if it is needed to restructure or refactor the imports.

About having different ways to require the same internal dependency: relative to file and absolute one, is not a good idea for the sake of clarity.

The "when in Rome" rule should be seen the opposite way; new implementations should follow what it was decided if there is no new agreement:
- to follow the common recommendation of not committing the `.env` file,
- use relative imports for internal dependencies.

**Pull request closed without merging**
